### ISSUE TITLE
How do you export the EasyOCR models to TorchScript format?

### ISSUE THREAD

**Issue by madsherlock** [ksasso1028/EasyOCR-cpp#6]
I would like to deploy EasyOCR models using libtorch, and saw your repo does this, which is excellent.

But the official EasyOCR models are not in TorchScript format needed by this software.

Do you have a conversion script or similar?

Specifically, I am having a hard time exporting the recognizer model - I don't know how to create the input tensor.

Best regards,
Mikael

**Comment by madsherlock** [comment]
For anyone wondering here's my code for exporting the detector model

```python
import easyocr
import easyocr.detection
import easyocr.recognition
import torch
import cv2
import numpy as np

craft_model_path = 'craft_mlt_25k.pth'
crnn_model_path = 'english_g2.pth'
image_path = 'sample_images/temp_image.png'

device = 'cuda'

canvas_size = 2560
mag_ratio = 1.

reader = easyocr.Reader(['en'], gpu=True, model_storage_directory='.', download_enabled=False)

# Convert CRAFT model to TorchScript
craftnet = reader.detector

img = cv2.imread(image_path, cv2.IMREAD_COLOR)
img_resized_list = []
imgr, target_ratio, size_heatmap = easyocr.imgproc.resize_aspect_ratio(img, canvas_size, interpolation=cv2.INTER_LINEAR, mag_ratio = mag_ratio)
img_resized_list.append(imgr)
x = [np.transpose(easyocr.imgproc.normalizeMeanVariance(n_img), (2, 0, 1)) for n_img in img_resized_list]
x = torch.from_numpy(np.array(x)).to(device)

traced_craft = torch.jit.trace(craftnet.module, x)
traced_craft.save(craft_model_path+'_traced.ts')
```

In the C++ code, I need to use `CraftModel::predictTuple()` instead of `CraftModel::predict()` inside `CraftModel::runDetector()` to get it to work in runtime.

I suspect it's because I am using a different EasyOCR version or something.

**Comment by ksasso1028** [comment]
I will try to work adding scripts to convert other easyOCR models and be able to handle other languages, just cant say when I will be able to get to it.

**Comment by ksasso1028** [comment]
The reason CRAFT does not return a tuple in this version is because I also removed the extra feature being returned, since is its not being used in the post processing steps to attain the bounding boxes. You can change if youd like here, or just use predictTuple to return the features if you would like to inspect them

https://github.com/JaidedAI/EasyOCR/blob/c999505ef6b43be1c4ee36aa04ad979175178352/easyocr/craft.py#L80

**Comment by madsherlock** [comment]
Thank you for your reply, it was very helpful, and I would consider the issue closed.

I actually got the recognizer to export to torchscript by giving it a dummy input text variable, and modifying C++ code to do the same, but the output text was garbage.

I kinda followed your steps regarding EasyOCR modification for recognizer model, and for those interested, here is my updated conversion script which will replace the forward() method of the recognizer model in order to drop the 'text' argument.

```python
import easyocr
import easyocr.detection
import easyocr.recognition
import easyocr.model.vgg_model
import torch
import cv2
import numpy as np
import types


# Modifies the forward() method to take only one argument 'input' and drop the 'text' argument which is unused anyway
def modRecognizerModule(recmodule):

    def moddedRecognizerForward(self, input):
        return self.oldForward(input, None)

    recmodule.oldForward = types.MethodType(easyocr.model.vgg_model.Model.forward, recmodule)
    recmodule.forward = types.MethodType(moddedRecognizerForward, recmodule)
    return recmodule


craft_model_path = 'craft_mlt_25k.pth'
crnn_model_path = 'english_g2.pth'
image_path = 'sample_images/temp_image.png'

device = 'cuda'

canvas_size = 2560
mag_ratio = 1.

reader = easyocr.Reader(['en'], gpu=True, model_storage_directory='.', download_enabled=False)

# Convert CRAFT model to TorchScript
craftnet = reader.detector

img = cv2.imread(image_path, cv2.IMREAD_COLOR)
img_resized_list = []
imgr, target_ratio, size_heatmap = easyocr.imgproc.resize_aspect_ratio(img, canvas_size, interpolation=cv2.INTER_LINEAR, mag_ratio = mag_ratio)
img_resized_list.append(imgr)
x = [np.transpose(easyocr.imgproc.normalizeMeanVariance(n_img), (2, 0, 1)) for n_img in img_resized_list]
x = torch.from_numpy(np.array(x)).to(device)

traced_craft = torch.jit.trace(craftnet.module, x)
traced_craft.save(craft_model_path+'_traced.ts')

# Convert CRNN model to TorchScript
recnet = reader.recognizer

recnet.module.forward = types.MethodType(moddedRecognizerForward, recnet.module)
rec_input_tensor = torch.randn(1,1,64,128).to(device)

traced_rec = torch.jit.trace(recnet.module, rec_input_tensor)
traced_rec.save(crnn_model_path+'_traced.ts')
```

This version would still require the use of `predictTuple()` instead of `predict()` for the CRAFT model.

However, it does not require any modifications to EasyOCR source code.

Now I still get the same garbage output from the recognizer model so I might post a new issue regarding that.
