### ISSUE TITLE
linux needs change in CmakeList.txt

### ISSUE THREAD

**Issue by rmsalinas** [ksasso1028/EasyOCR-cpp#7]
Hi,
in order to compile in linux you need to add
set(CMAKE_CXX_STANDARD 20)

**Comment by ksasso1028** [comment]
thanks @rmsalinas , this has been fixed in [9ea98a5](https://github.com/ksasso1028/EasyOCR-cpp/commit/9ea98a57e983f401a62af23671bb958877a84a75)
