### ISSUE TITLE
output text doesn't match with actual image

### ISSUE THREAD

**Issue by thietnp** [ksasso1028/EasyOCR-cpp#9]
I run the torchTest program with input is test.jpg in the repo but the output doesn't match with actual image. Each character is shifted to right one unit.
Ex: text in image is THREE, output  is UISFF
T        -> U
H        -> I
R       -> S
E        -> F
E        -> F

**Comment by thietnp** [comment]
[text on console.txt](https://github.com/ksasso1028/EasyOCR-cpp/files/15038057/text.on.console.txt)
![output-heatmap](https://github.com/ksasso1028/EasyOCR-cpp/assets/33216570/03ac7f76-89a6-4957-b2b1-35cf7484b097)
![test](https://github.com/ksasso1028/EasyOCR-cpp/assets/33216570/c5df3530-0228-4457-9a93-7ccecef17bd0)

**Comment by ksasso1028** [comment]
hi, are you using the latest branch? I made an update yesterday to fix this

**Comment by ksasso1028** [comment]
The commit message is: https://github.com/ksasso1028/EasyOCR-cpp/commit/28da1ffe9487eea30f0a7bd90b49b0ee0d449b7a

**Comment by thietnp** [comment]
Great! Thanks. It works well.

**Comment by ksasso1028** [comment]
awesome, closing this issue
